# Generated by Django 6.0.7 on 2026-08-04 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventmember_checked_in_at_eventmember_is_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='qr_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                
            ),
        ),]
