# Generated by Django 6.0.7 on 2026-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventmember_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
