# Generated by Django 6.0.7 on 2026-08-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_banner_eventfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qr_codes/'),
        ),
    ]
