services:
  - type: web
    name: event-registration
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py create_deploy_admin && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SITE_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: event-registration-db
          property: connectionString
      - key: DJANGO_ADMIN_USERNAME
        sync: false
      - key: DJANGO_ADMIN_PASSWORD
        sync: false
      - key: DJANGO_ADMIN_EMAIL
        sync: false

databases:
  - name: event-registration-db
    plan: free
