# Generated by Django 6.0.7 on 2026-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customization_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='primary_color',
            field=models.CharField(default='#3d4044', max_length=7),
        ),
    ]
