# Generated by Django 6.0.7 on 2026-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customization_primary_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='primary_color',
            new_name='sidebar_color',
        ),
        migrations.AddField(
            model_name='customization',
            name='topbar_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
