# Generated by Django 6.0.7 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/default.jpeg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
