# Generated by Django 6.0.7 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_customization",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
